### ISSUE TITLE
Windows running returns error: [WinError 10013]

### ISSUE THREAD

**Issue by pioneerAlone** [rolandbaer/udp-echo-server#9]
E:\Test Server\python\udp-echo-server-master>py -3 udpecho.py -S
Traceback (most recent call last):
  File "E:\Test Server\python\udp-echo-server-master\udpecho.py", line 214, in <module>
    start_server(ARGS)
  File "E:\Test Server\python\udp-echo-server-master\udpecho.py", line 158, in start_server
    sender = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_RAW)
  File "C:\Program Files\Python39\lib\socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [WinError 10013] An attempt was made to access the socket in a way that is not permitted by the access permissions.
It seems to be the problem caused by "sender = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_RAW)", but the reason is not clear

**Comment by rolandbaer** [comment]
it looks like using raw sockets is not allowed under windows 10 ( https://stackoverflow.com/a/69668734/17646 ). But this is not directly addressed by this issue and will be hadled in the issue #12.
